import assert from 'node:assert/strict';
export async function checkAnimations({call,evaluate,until,base,capture}){
  const click=label=>evaluate(`Array.from(document.querySelectorAll('button')).find(b=>b.textContent===${JSON.stringify(label)}).click()`);
  const read=()=>evaluate(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc`);
  await call('Page.navigate',{url:base});
  await until(`!!document.querySelector('#account-slot button') && document.body.innerText.includes('On this device')`);
  await evaluate(`document.querySelector('#new-menu-button').click()`);
  assert.equal(await evaluate(`document.querySelector('#new-menu').hidden`),false);
  assert(await evaluate(`document.querySelector('#new-drawing-link').href.includes('/draw/?')`));
  const animationUrl=await evaluate(`document.querySelector('#new-animation-link').href`);
  assert(animationUrl.includes('/animate/'));
  await capture('new-creation-menu.png');
  await call('Page.navigate',{url:animationUrl});
  await until(`document.querySelector('.animation-editor') && document.body.innerText.includes('Saved on this device')`);
  await click('Carbonyl example');
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.initial?.atoms?.length===6`);
  const initial=await read();
  const canvasClick=async(x,y)=>{
    const p=await evaluate(`(()=>{const c=document.querySelector('canvas'),r=c.getBoundingClientRect(),v=JSON.parse(c.dataset.view);return {x:r.left+(${x}*v.scale+v.x)/1000*r.width,y:r.top+(${y}*v.scale+v.y)/600*r.height};})()`);
    await call('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});
  };
  await canvasClick(235,190);await canvasClick(430,280);
  await until(`document.body.innerText.includes('invalid valence')`);
  await click('Complete animation');
  assert.equal(await evaluate(`!!document.querySelector('[aria-label="Animation canvas"]')`),false,'Invalid step played');
  await canvasClick(430,237.5);await canvasClick(430,195);
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[0]?.after?.atoms.length===6`);
  await capture('animation-step-editor.png');
  await click('+ Next step');
  await until(`document.querySelectorAll('.reaction-step').length===2`);
  let doc=await read();
  assert.equal(doc.steps[0].after.atoms.find(a=>a.id==='O1').charge,-1);
  assert.equal(doc.steps[0].after.bonds.find(b=>b.id==='B1').order,1);
  await click('Use example arrows');
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[1]?.after?.atoms.find(a=>a.id==='O2').charge===-1`);
  doc=await read();assert.deepEqual(doc.initial,initial.initial);
  await capture('animation-two-steps.png');
  const local=await evaluate(`new URL(location.href).searchParams.get('local')`);
  await call('Page.reload');await until(`document.querySelector('.animation-editor') && document.body.innerText.includes('Saved on this device')`);
  assert.equal((await read()).steps.length,2);
  await click('Edit starting molecules');
  await until(`document.querySelector('iframe')?.contentDocument?.body.innerText.includes('Saved on this device') && !!document.querySelector('iframe').contentDocument.querySelector('canvas')`);
  await capture('animation-drawing-tools.png');
  await click('Use these molecules');
  await until(`!document.querySelector('iframe') && JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.kind==='animation'`);
  const edited=await read();
  assert.deepEqual(edited.initial.atoms.map(a=>a.id),initial.initial.atoms.map(a=>a.id));
  assert(edited.steps[1].after,'Drawing editor lost existing arrow attachments');
  await evaluate(`(()=>{const s=document.querySelector('.animation-transport select');s.value='2';s.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await click('Complete animation');
  await until(`Number(document.querySelector('[aria-label="Animation progress"]').value)>1.05`);
  assert.equal(await evaluate(`document.querySelectorAll('.reaction-step').length`),0);
  await click('Pause');await capture('animation-playback.png');
  await click('Stop');
  assert.equal(await evaluate(`document.querySelectorAll('.reaction-step').length`),2);
  // Editing upstream invalidates cached products downstream; completion cannot play stale chemistry.
  await evaluate(`document.querySelector('[aria-label="Remove arrow 2"]').click()`);
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[1].after===null`);
  await click('Complete animation');
  assert.equal(await evaluate(`!!document.querySelector('[aria-label="Animation canvas"]')`),false);
  await click('Undo');
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[1].after!==null`);
  await click('Complete animation');await click('Pause');
  await evaluate(`document.querySelector('.animation-menu').open=true`);
  await evaluate(`window.__animationExports=[];const original=URL.createObjectURL;URL.createObjectURL=function(blob){window.__animationExports.push(blob);return original.call(this,blob)};HTMLAnchorElement.prototype.click=function(){};`);
  await click('Export GIF');
  for(let i=0;i<120;i++){if(await evaluate(`window.__animationExports.length>0`))break;await new Promise(r=>setTimeout(r,250));}
  const gif=await evaluate(`(async()=>{const b=window.__animationExports[0];return b?{type:b.type,size:b.size,header:new TextDecoder().decode((await b.arrayBuffer()).slice(0,6))}:null})()`);
  assert(gif&&gif.type==='image/gif'&&gif.size>1000&&gif.header==='GIF89a','Invalid GIF export');
  // Faster video export to keep this integration test short.
  await evaluate(`(()=>{const select=document.querySelector('.animation-transport select');select.value='2';select.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await click('Export video');
  for(let i=0;i<100;i++){if(await evaluate(`window.__animationExports.length>1`))break;await new Promise(r=>setTimeout(r,200));}
  assert(await evaluate(`window.__animationExports[1]?.type==='video/webm' && window.__animationExports[1]?.size>1000`),'Video export missing');
  await call('Page.navigate',{url:base});await until(`!!document.querySelector('#account-slot button') && document.body.innerText.includes('On this device')`);await evaluate(`document.querySelector('#nav-animations').click()`);
  await capture('animation-library-debug.png');
  await until(`!!document.querySelector('.drawing-card[href*="${local}"]')`);
  assert(await evaluate(`document.querySelector('.drawing-card[href*="${local}"]').href.includes('kind=animation')`));
  await capture('animation-library.png');
  console.log('PASS: Sequential step editing, invalidation, automatic playback and stop, save/reload, GIF/WebM export, and separate library');
}
