import assert from 'node:assert/strict';
export async function checkAnimations({call,evaluate,until,base,capture}){
  const click=label=>evaluate(`Array.from(document.querySelectorAll('button')).find(b=>b.textContent===${JSON.stringify(label)}).click()`);
  const read=()=>evaluate(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc`);
  await call('Page.navigate',{url:base});
  await until(`!!document.querySelector('#account-slot button') && document.body.innerText.includes('On this device')`);
  await evaluate(`document.querySelector('#new-menu-button').click()`);
  assert.equal(await evaluate(`document.querySelector('#new-menu').hidden`),false);
  assert(await evaluate(`document.querySelector('#new-drawing-link').href.includes('/draw/?')`));
  const animationUrl=await evaluate(`document.querySelector('#new-animation-link').href`);
  assert(animationUrl.includes('/animate/'));
  await capture('new-creation-menu.png');
  await call('Page.navigate',{url:animationUrl});
  await until(`document.querySelector('.animation-editor') && document.body.innerText.includes('Saved on this device')`);
  await until(`!!document.querySelector('.animation-drawing-tools [title="Benzene ring (R)"]')`);
  assert.equal(await evaluate(`!!document.querySelector('iframe')`),false,'Drawing tools should be in the step, not a dialog');
  assert(await evaluate(`!!document.querySelector('.animation-inspector .animation-steps-menu button')`));
  const canvasClick=async(x,y)=>{
    const p=await evaluate(`(()=>{const c=document.querySelector('[aria-label="Chemical drawing canvas"]'),r=c.getBoundingClientRect(),d=JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[Number(document.querySelector('.reaction-step.active').dataset.step)-1].drawing;return {x:r.left+(${x}+d.offset.x)*d.scale,y:r.top+(${y}+d.offset.y)*d.scale};})()`);
    await call('Input.dispatchMouseEvent',{type:'mouseMoved',...p});await call('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});
  };
  await evaluate(`document.querySelector('[title="Benzene ring (R)"]').click()`);
  await canvasClick(220,170);
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[0].drawing.segments.length===6`);
  await capture('animation-inline-drawing.png');
  const local=await evaluate(`new URL(location.href).searchParams.get('local')`);
  assert.equal(await evaluate(`JSON.parse(localStorage.getItem('openreactions.localDocument.'+${JSON.stringify(local)})).doc.kind`),'animation');
  await evaluate(`document.querySelector('.animation-drawing-tools button[title="Undo (Cmd/Ctrl+Z)"]')?.click()`);
  // The exact drawing palette exposes Erase All, including its normal confirmation.
  await evaluate(`Array.from(document.querySelectorAll('.animation-drawing-tools button')).find(b=>b.textContent.trim()==='Erase All').click()`);
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[0].drawing.vertices.length===0`);
  await click('Carbonyl example');
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.initial?.atoms?.length===6`);
  const initial=await read();
  await evaluate(`document.querySelector('[aria-label="Curved arrow shortcuts"] > button[aria-pressed]').click()`);
  await canvasClick(235,190);await canvasClick(430,280);
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[0].drawing.arrows.length===1`);
  await click('Complete animation');
  await until(`document.body.innerText.includes('invalid valence')`);
  assert.equal(await evaluate(`!!document.querySelector('[aria-label="Animation canvas"]')`),false,'Invalid step played');
  await canvasClick(430,237.5);await canvasClick(430,195);
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[0].drawing.arrows.length===2`);
  await capture('animation-step-editor.png');
  await click('+ Next step');
  await until(`document.querySelectorAll('.reaction-step').length===2`);
  let doc=await read();
  assert.equal(doc.steps[0].after.atoms.find(a=>a.id==='O1').charge,-1);
  assert.equal(doc.steps[0].after.bonds.find(b=>b.id==='B1').order,1);
  assert.equal(doc.steps[1].startScene.atoms.find(a=>a.id==='O1').charge,-1);
  assert.equal(doc.steps[1].startScene.bonds.filter(b=>b.from==='C1'||b.to==='C1').length,4);
  await click('Use example arrows');
  await click('Check electron movements');
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[1]?.after?.atoms.find(a=>a.id==='O2').charge===-1`);
  doc=await read();assert.deepEqual(doc.initial,initial.initial);
  await capture('animation-two-steps.png');
  // The second box has real drawing tools, but cannot silently change the intermediate chemistry.
  await evaluate(`document.querySelector('[title="Add positive charge (G)"]').click()`);
  await canvasClick(430,195);
  await capture('animation-charge-edit.png');
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[1].drawing.vertexAtoms['430.00,195.00'].charge===1`);
  await click('Complete animation');
  await until(`document.body.innerText.includes('must match the previous product')`);
  assert.equal(await evaluate(`!!document.querySelector('[aria-label="Animation canvas"]')`),false);
  await click('Use recommended structure');
  await until(`!document.body.innerText.includes('must match the previous product')`);
  await click('Use example arrows');
  await click('Check electron movements');
  await until(`JSON.parse(localStorage.getItem('openreactions.draft.local')).doc.steps[1]?.after?.atoms.find(a=>a.id==='O2').charge===-1`);
  await call('Page.reload');await until(`document.querySelector('.animation-editor') && document.body.innerText.includes('Saved on this device')`);
  assert.equal((await read()).steps.length,2);
  await evaluate(`(()=>{const s=document.querySelector('.animation-transport select');s.value='2';s.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await click('Complete animation');
  await until(`Number(document.querySelector('[aria-label="Animation progress"]').value)>1.05`);
  assert.equal(await evaluate(`document.querySelectorAll('.reaction-step').length`),0);
  assert(await evaluate(`(()=>{const c=document.querySelector('[aria-label="Animation canvas"]'),r=c.getBoundingClientRect(),p=c.getContext('2d').getImageData(0,0,1000,600).data;let n=0;for(let i=0;i<p.length;i+=4)if(p[i]<80&&p[i+1]<80&&p[i+2]<80)n++;return r.width>300&&r.height>150&&n>100;})()`),'Playback is blank or clipped');
  await click('Pause');await capture('animation-playback.png');
  await click('Stop');
  await until(`document.querySelectorAll('.reaction-step').length===2 && !!document.querySelector('.animation-drawing-tools [title="Draw (D)"]')`);
  await click('Complete animation');await until(`!!document.querySelector('[aria-label="Animation canvas"]')`);await click('Pause');
  await evaluate(`document.querySelector('.animation-menu').open=true`);
  await evaluate(`window.__animationExports=[];const original=URL.createObjectURL;URL.createObjectURL=function(blob){window.__animationExports.push(blob);return original.call(this,blob)};HTMLAnchorElement.prototype.click=function(){};`);
  await click('Export GIF');
  for(let i=0;i<120;i++){if(await evaluate(`window.__animationExports.length>0`))break;await new Promise(r=>setTimeout(r,250));}
  const gif=await evaluate(`(async()=>{const b=window.__animationExports[0];return b?{type:b.type,size:b.size,header:new TextDecoder().decode((await b.arrayBuffer()).slice(0,6))}:null})()`);
  assert(gif&&gif.type==='image/gif'&&gif.size>1000&&gif.header==='GIF89a','Invalid GIF export');
  // Faster video export to keep this integration test short.
  await evaluate(`(()=>{const select=document.querySelector('.animation-transport select');select.value='2';select.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await click('Export video');
  for(let i=0;i<100;i++){if(await evaluate(`window.__animationExports.length>1`))break;await new Promise(r=>setTimeout(r,200));}
  assert(await evaluate(`window.__animationExports[1]?.type==='video/webm' && window.__animationExports[1]?.size>1000`),'Video export missing');
  await call('Page.navigate',{url:base});await until(`!!document.querySelector('#account-slot button') && document.body.innerText.includes('On this device')`);await evaluate(`document.querySelector('#nav-animations').click()`);
  await capture('animation-library-debug.png');
  await until(`!!document.querySelector('.drawing-card[href*="${local}"]')`);
  assert(await evaluate(`document.querySelector('.drawing-card[href*="${local}"]').href.includes('kind=animation')`));
  await capture('animation-library.png');
  console.log('PASS: Sequential step editing, invalidation, automatic playback and stop, save/reload, GIF/WebM export, and separate library');
}
